cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(pico_uart_bridge C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(pico_uart_bridge main.c usb_descriptors.c)
pico_generate_pio_header(pico_uart_bridge ${CMAKE_CURRENT_LIST_DIR}/uart.pio)
target_include_directories(pico_uart_bridge PRIVATE ${CMAKE_CURRENT_LIST_DIR})
target_link_libraries(pico_uart_bridge PRIVATE pico_stdlib pico_multicore
    pico_unique_id hardware_pio hardware_clocks tinyusb_device tinyusb_board)
target_compile_options(pico_uart_bridge PRIVATE -Wall -Wextra)
pico_enable_stdio_usb(pico_uart_bridge 0)
pico_enable_stdio_uart(pico_uart_bridge 0)
pico_set_program_name(pico_uart_bridge "PIO UART Bridge")
pico_set_program_version(pico_uart_bridge "0.1.0")
pico_add_extra_outputs(pico_uart_bridge)
